services:
  - type: web
    name: ai-career-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard.app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_RECEIVER
        sync: false

  - type: cron
    name: ai-career-cron
    runtime: python
    schedule: "0 */6 * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_RECEIVER
        sync: false
